package main

import (
	"context"
	"log"
	"net/http"

	usersv1 "github.com/az5840/connect-go-example/gen/users/v1"        // generated by protoc-gen-go
	"github.com/az5840/connect-go-example/gen/users/v1/usersv1connect" // generated by protoc-gen-connect-go

	"connectrpc.com/connect"
)

func main() {
	client := usersv1connect.NewUsersServiceClient(
		http.DefaultClient,
		"http://localhost:8080",
	)
	res, err := client.GetUser(
		context.Background(),
		connect.NewRequest(&usersv1.GetUserRequest{
			Id: 3,
		}),
	)
	if err != nil {
		log.Println(err)
		return
	}
	log.Println(res.Msg.Name)
}
